.PHONY: clean

clean:
	rm -rf d05/logs
	rm -rf d05/staticfiles
	rm -rf d05/db.sqlite3
	rm -rf d05/d05/__pycache__
	rm -rf d05/ex00/__pycache__
	rm -rf d05/ex01/__pycache__
	rm -rf d05/ex02/__pycache__
	rm -rf d05/logs/form_submissions.log
	find . -name "*.pyc" -exec rm -f {} \;
